{{- $root :=. -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{  .Values.apiservice.name }}-deployment"
  labels:
    {{- range .Values.apiservice.labels }}
    {{ .name }}: {{ .value }}
    {{- end }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.apiservice.replicaCount }}
  selector:
    matchLabels:
      {{- range .Values.apiservice.labels }}
      {{ .name }}: {{ .value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range .Values.apiservice.labels }}
        {{ .name }}: {{ .value }}
        {{- end }}
    spec:
      {{ if .Values.apiservice.affinity }}
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: {{ .Values.apiservice.affinity.key }}
                 operator: In
                 values:
                 - {{ .Values.apiservice.affinity.value }}
      {{- end }}     
      containers:
      - name: "{{  .Values.apiservice.name }}"
        image: "{{ .Values.apiservice.image }}:{{ .Chart.Version }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: defaultport
          containerPort: {{ .Values.apiservice.podport}}
        resources:
          requests:
            cpu: {{ .Values.apiservice.requests.cpu }}
            memory: {{ .Values.apiservice.requests.memory }}
          limits:
            cpu: {{ .Values.apiservice.limits.cpu }}
            memory: {{ .Values.apiservice.limits.memory }}
        {{- if or .Values.apiservice.configmaps .Values.apiservice.secrets }}
        envFrom:
          {{- if .Values.apiservice.configmaps }}
          {{- range .Values.apiservice.configmaps }}
          - configMapRef:
              name: "{{ $root.Values.apiservice.name }}-{{ .name }}"
              {{- end }}
          {{- end}}
          {{- if .Values.apiservice.secrets }}
          {{- range .Values.apiservice.secrets }}
          - secretRef:
              name: "{{ $root.Values.apiservice.name }}-{{ .name }}"
              {{- end }}
          {{- end}}
        {{- end}}
      {{- if .Values.apiservice.conf }}
        volumeMounts:
        - name: {{ .Values.apiservice.name}}
          mountPath: {{ .Values.apiservice.conf.mountPath }} # This should be your final destination
          subPath: {{ .Values.apiservice.conf.subPath }} 
      volumes:
      - name: {{ .Values.apiservice.name}}  # To access this volume, this name must be used inside volumeMounts of the container
        configMap:
           name: {{ .Values.apiservice.conf.datacmap }}
      {{- end}} 

