{{- $root :=. -}}
{{- if .Values.secret }}
{{- range .Values.apiservice.secrets }}
{{- $outer := . -}}
{{- range $root.Values.secret }}
{{- if eq .name $outer.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $root.Values.apiservice.name }}-{{ .name }}"
  namespace: {{ $root.Values.namespace }}

type: {{ .type }}
data:
  {{- range .vars }}
  {{ .name }}: {{ .value }}
  {{- end}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}